version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-247-79-178.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: d48hv0js9iaakn
            ssl: true
            user: iexeoxxeopgjkb
            password: 30df86db5c3ab3d25264064b750183e560eb2a57ef5de62679cf9c3562d97ffb
            migrations: true